### ISSUE TITLE
Доступ к видео

### ISSUE THREAD

**Issue by MVjimbo** [AWedASTera/Video-Archive-SPBU#1]
Можем ли мы устанавливать что-либо на сервера, хранящие видео?

**Comment by AWedASTera** [comment]
Похоже что да. Пробуем вариант с wowza streaming engine

**Comment by AWedASTera** [comment]
Удалось развернуть nimble streamer на удаленном сервере и с него получить ссылку на vod. Видео с ссылки прекрасно работает локальном youphptube

**Comment by AWedASTera** [comment]
Поддерживаемые форматы видео (которые можно транслировать с чужого сервера): mp4, webm, mkv, ogv, flv. Кроме того, видео с форматами поддерживаемыми ffmpeg можно загружать в хранилище video cms и перевести при помощи encoder'а в формат подходящий для трансляции.
